# Foreground, Background, and Cursor colors
[colors.primary]
foreground = "#FFF9E6"  # Creamy White
background = "#120715"  # Dark Plum
bright_foreground = "#FFF9E6"      # Creamy White

# Normal colors
[colors.normal]
black = "#333333"
red = "#F51720"         # Chili Pepper
green = "#00FF00"       # Green
yellow = "#F8D210"      # Gold
blue = "#00FFFB"        # Light Blue
magenta = "#FA26A0"     # Pink
cyan = "#2FF3E0"        # Cyan
white = "#FFF9E6"       # Creamy White

# Bright colors
[colors.bright]
black = "#333333"
red = "#F51720"         # Chili Pepper
green = "#00FF00"       # Green
yellow = "#F8D210"      # Gold
blue = "#00FFFB"        # Light Blue
magenta = "#FA26A0"     # Pink
cyan = "#2FF3E0"        # Cyan
white = "#FFF9E6"       # Creamy White

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.search.focused_match]
background = "#F8D210"      # Gold
foreground = "#120715"  # Dark Plum
